package advancedProjectComputer;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class EmployeeControlEventController {
	@FXML
	private Button adminAddCategory;
	@FXML
	private Button adminEditCategory;
	@FXML
	private Button employeeHome;
	@FXML
	private Button EmployeeSignOut;

	// Event Listener on Button[#adminAddCategory].onAction
	@FXML
	public void selectAddCategory(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#adminEditCategory].onAction
	@FXML
	public void selectEditCategory(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#employeeHome].onAction
	@FXML
	public void selectHome(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#EmployeeSignOut].onAction
	@FXML
	public void employeeSignOut(ActionEvent event) {
		// TODO Autogenerated
	}
}
